const data = {
  services: [
    {
      name: 'Leaks maintenance',
      slug: 'Leaks-maintenance',
      category: 'plumbing',
      image: '/images/p1.jpg',
      price: 1000,
      countInAvailable: 10,
      provider: 'John',
      rating: 4.5,
      numReviews: 10,
      discription: 'Professional and high-quality maintenance of leaks',
    },
    {
      name: 'Drain blockage maintenance',
      slug: 'drain-blockage-maintenance',
      category: 'plumbing',
      image: '/images/p2.jpg',
      price: 500,
      countInAvailable: 20,
      provider: 'Savy',
      rating: 3.5,
      numReviews: 25,
      discription: 'Professional and high-quality maintenance',
    },
    {
      name: 'Kitchen maintenance',
      slug: 'kitchen-maintenance',
      category: 'plumbing',
      image: '/images/p3.jpg',
      price: 800,
      countInAvailable: 5,
      provider: 'Khalid',
      rating: 4.5,
      numReviews: 2,
      discription: 'Professional and high-quality maintenance',
    },
    {
      name: 'Faucets maintenance',
      slug: 'faucets-maintenance',
      category: 'plumbing',
      image: '/images/p4.jpg',
      price: 200,
      countInAvailable: 30,
      provider: 'Ahmed',
      rating: 5,
      numReviews: 30,
      discription: 'Professional and high-quality maintenance',
    },
  ],
};

export default data;
